### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by sannykr** [praekelt/swagger-django-generator#6]
Could you please add license file. I am trying to push this package to conda, and since you don't have the license, I can't do that.

**Comment by sannykr** [comment]
Also, if you could clarify which BSD license(BSD-3-clause or BSD-2-clause or other), it would be a helpful for me. You have mentioned only BSD that is the name of license family.

**Comment by sannykr** [comment]
@praekelt: following up

**Comment by cobusc** [comment]
@sannykr I will add a license ASAP.

**Comment by cobusc** [comment]
@sannykr I added the BSD 3-clause license

**Comment by sannykr** [comment]
@cobusc : Thanks.
